version: '3.7'
services:
  grakn:
    image: graknlabs/grakn:1.5.9
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    deploy:
      resources:
        limits:
          cpus: '2.1'
          memory: 8193M
        reservations:
          cpus: '2'
          memory: 8192M
    restart: always
  redis:
    image: redis:5.0.5
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: 501M
        reservations:
          cpus: '1'
          memory: 500M
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          cpus: '2.1'
          memory: 1025M
        reservations:
          cpus: '2'
          memory: 1024M
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin123
      MINIO_SECRET_KEY: admin123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: 1025M
        reservations:
          cpus: '1'
          memory: 1024M
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin123
      - RABBITMQ_DEFAULT_PASS=admin123
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: 501M
        reservations:
          cpus: '1'
          memory: 500M    
    restart: always
  opencti:
    image: opencti/platform:2.1.4
    environment:
      - APP__PORT=80
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=admin123
      - APP__ADMIN__TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=admin123
      - MINIO__SECRET_KEY=admin123
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=admin123
      - RABBITMQ__PASSWORD=admin123
    ports:
      - "80:80"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: 801M
        reservations:
          cpus: '1'
          memory: 800M
    restart: always
  worker:
    image: opencti/worker:2.1.4
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1.1'
          memory: 1001M
        reservations:
          cpus: '1'
          memory: 1000M
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=fe795b8e-b12c-4ddb-8cee-e5554ea62d48   # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=e58db32c-4354-4bd8-af1e-b9fc45f67920   # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=2e8e0edb-29ba-4805-b029-0fd13d3ef2bd
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M 
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=f428adb8-50af-49bd-94f3-89ab09516bf3  # Valid UUDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=identity,sector,region,country,city
      - CONNECTOR_CONFIDENCE_LEVEL=4
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=1 # Days
    depends_on:
      - opencti
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=8e601a18-2125-47f6-8f7f-ca9466efbf33 # Valid UUDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=5
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_INTERVAL=1 # Days
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M 
    restart: always
  connector-amitt:
    image: opencti/connector-amitt:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=8ec0c6c0-9731-4088-80f8-627033a28f45
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AM!TT
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=6
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - AMITT_FILE_URL=https://raw.githubusercontent.com/VVX7/cti/master/amitt-attack/amitt-attack.json
      - PRE_AMITT_FILE_URL=https://raw.githubusercontent.com/VVX7/cti/master/amitt-pre-attack/amitt-pre-attack.json
      - AMITT_INTERVAL=1 # Days
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-cve:
    image: opencti/connector-cve:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=40e6ecee-e6e4-4c4c-aa6c-f1f091443d37
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=7
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
      - CVE_INTERVAL=1 # Days
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-ipinfo:
    image: opencti/connector-ipinfo:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=e6c3c6f3-347e-4887-b451-0a4c75cdf269
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE='ipv4-addr'
      - CONNECTOR_CONFIDENCE_LEVEL=8
      - CONNECTOR_LOG_LEVEL=info
      - IPINFO_TOKEN=7a024374-5f47-4f67-be59-77c10ed0d46d
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
  connector-misp:
    image: opencti/connector-misp:latest
    environment:
      - OPENCTI_URL=http://opencti:80
      - OPENCTI_TOKEN=c39d93ad-0f96-4716-92e3-635614e39dd7
      - CONNECTOR_ID=77edf542-7c31-481d-9727-d5584a845349
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=9
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=http://localhost:9090 # Required
      - MISP_KEY=admin123 # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP\ event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2010-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=1 # Required, in minutes
    deploy:
      resources:
        limits:
          cpus: '0.51'
          memory: 223M
        reservations:
          cpus: '0.5'
          memory: 222M
    restart: always
volumes:
  grakndata:
  esdata:
  s3data:
